version: 0.0.{build}

pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2017

platform:
  - x86
  - x64

branches:
  only:
    - master

environment:
  matrix:
    - flavor: msvc
      QTDIR: C:\Qt\5.12\msvc2017
      MAKE: "nmake /NOLOGO"

init:
  - set PATH=%QTDIR%\bin;%PATH%
  - set FVI_HOME=C:\hello\world

before_build:
  - if %platform%==x86 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat" x86
  - if %platform%==x64 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - git submodule update --init

build_script:
  - md build
  - cd build
  - qmake ..
  - "%MAKE%"
  - "%MAKE% check"
  - "%MAKE% install"

  - windeployqt
      --release
      --plugindir C:\fvi-launcher\lib
      --qmldir ..
      --no-translations
      --no-opengl-sw
      C:\fvi-launcher
  - md C:\fvi-launcher\lib\qml
  - ps: Get-ChildItem C:\fvi-launcher -Filter 'Qt*' -Directory |
      Move-Item -Destination C:\fvi-launcher\lib\qml

  - copy ..\README.md C:\fvi-launcher
  - copy ..\LICENSE.md C:\fvi-launcher
  - git describe --always > tmp_out.txt
  - set /p SUFFIX=<tmp_out.txt
  - 7z a fvi-launcher_%SUFFIX%_win-%platform%.zip C:\fvi-launcher

artifacts:
  - path: build\fvi-launcher_*.zip
