language: cpp

sudo: required
dist: bionic

branches:
  only:
    - master

env:
  global:
    - QT_VER=5.15.1

git:
  depth: 1000


install: .travis/install.sh
script: .travis/script.sh

jobs:
  include:

# LINUX build
    - os: linux
      env: TARGET=x11-static

services:
  - xvfb
